#!/usr/bin/env bash
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$$.tags" "tags"
