name: base
channels:
- conda-forge
- defaults
- conda-canary
dependencies:
- python>=3.7
# - black
- cookiecutter
# - jedi
# - mypy
- nodejs
- pandoc>=2.2
# - pydocstyle
# - python-language-server
# - vulture
- pip:
  # - bandit
  - editorconfig
  # - jupyter_contrib_nbextensions
  - MarkdownPP
  # - nbdime
  - panflute
  - vim-vint
