name: base
channels:
- defaults
- conda-forge
- pscondaenvs
dependencies:
- anaconda
- pandoc>=2.2
- pscondaenvs
- nodejs
- pip:
  - black
  - cookiecutter
  - editorconfig
  - jupyter_contrib_nbextensions
  - MarkdownPP
  - mypy
  - nbdime
  - panflute
  - vim-vint
