name: base
channels:
- conda-forge
- defaults
- conda-canary
dependencies:
- python>=3.7
- pandoc>=2.2
- nodejs
- mypy
- black
- cookiecutter
- pip:
  - editorconfig
  # - jupyter_contrib_nbextensions
  - MarkdownPP
  # - nbdime
  - panflute
  - vim-vint
