# name: C:\Users\jfishe\Anaconda3
name: base
channels:
- defaults
- conda-forge
- pscondaenvs
dependencies:
- anaconda
- pandoc>=2.1
- pscondaenvs
- nodejs
- pip:
  - cookiecutter
  - editorconfig
  - jupyter_contrib_nbextensions
  - nbdime
  - mypy
  - vim-vint
  - virtualenv
  - shortcutter
  - panflute
# prefix: C:\Users\fishe\Anaconda3
