name: vim_python
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- black
- isort
- mypy
- nodejs
- pandoc
- panflute
- pip
- pydocstyle
- pylint
- ripgrep
- pip:
  - MarkdownPP
  - vim-vint
