# name: C:\Users\jfishe\Anaconda3
name: base
channels:
- defaults
dependencies:
- anaconda
- pip:
  - click
  - cookiecutter
  - editorconfig
  - jupyter_contrib_nbextensions
  - nbdime
  - mypy
  - vim-vint
  - virtualenv
# prefix: C:\Users\fishe\Anaconda3
