channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - chardet # Added by conda-export
  - lazy-object-proxy # Added by conda-export
  - mypy
  - nodejs
  - pandoc
  - panflute
  - pip
  - pydocstyle
  - pylint
  - python-dateutil # Required by vimfiles/UltiSnips/vimwiki.snippets
  - python[version='>=3.10']
  - ripgrep
  - watchdog # Added by conda-export
  - wrapt # Added by conda-export
  - pip:
    - markdownpp
    - vim-vint
name: vim_python
