channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - chardet
  - condax
  - mypy
  - nodejs
  - panflute
  - pip
  - pipx
  - pydocstyle
  - pylint
  - pypandoc
  - python-dateutil
  - python[version='>=3.11']
  - ripgrep
  # - starship # Uncomment if not installed elsewhere.
  - watchdog
  - pip:
    - markdownpp
    - panvimwiki
    - vim-vint
name: vim-python
