name: base
channels:
- conda-forge
- defaults
# - conda-canary
dependencies:
# - black
# - cookiecutter
# - jedi
# - mypy
- nodejs
- pandoc
- panflute
- pip
# - pydocstyle
# - python-language-server
# - vulture
- pip:
  # - bandit
  # - editorconfig editorconfig-vim no longer requires.
  # - jupyter_contrib_nbextensions
  # - dovpanda
  - MarkdownPP
  # - nbdime
  # - vim-vint
