# To recreate:
#   conda env export --file environment.yml --from-history
# Uv and pip should use requirements.txt.
# Select python<3.12 to match vim --version.
name: vim-python
channels:
  - conda-forge
  - defaults
dependencies:
  - bat
  - chardet
  - condax
  - mypy
  - nodejs
  - pandoc [version='>=3.5']
  - panflute [version='<2.1']
  - pypandoc
  - python [version='<3.12']
  # Uncomment if not installed elsewhere.
  # - ruff
  # - ripgrep
  # - starship
  # uv pip install --requirement requirements.txt
