channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - chardet
  - mypy
  - nodejs
  - panflute
  - pip
  - pydocstyle
  - pylint
  - pypandoc
  - python-dateutil
  - python[version='>=3.11']
  - ripgrep
  - watchdog
  - pip:
    - markdownpp
    - panvimwiki
    - vim-vint
name: vim-python
