channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - python-dateutil
  # - chardet
  # - isort
  # - lazy-object-proxy
  - mypy
  - nodejs
  - pandoc
  - panflute
  - pip
  - pydocstyle
  # - pylint
  - python[version='>=3.10']
  - ripgrep
  # - watchdog
  # - wrapt
  - pip:
    - markdownpp
    - vim-vint
name: vim_python
