# To recreate:
#   conda env export --file environment.yml --from-history
# Uv and pip should use requirements.txt.
# Select python<3.12 to match vim --version.
name: vim-python
channels:
  - conda-forge
dependencies:
  - condax
  - nodejs
  - python # [version='<3.12']
  - vim
  # Uncomment if not installed elsewhere.
  # - mypy
  # - pls
  # - rich-cli
  # - ruff
  # - starship
# Run the following to install:
  # uv pip install --requirement requirements.txt
  # uv tool install mypy
  # uv tool install pls
  # uv tool install rich-cli
  # Vim
  #   :h fzf-vim-dependencies
  #   :h fzf-vim-completion-functions
  # winget import --import-file winget.json
  # winget export --output=winget.json
  # END fzf-vim-dependencies
