name: base
channels:
- defaults
- conda-forge
- conda-canary
dependencies:
- conda>=4.6
- anaconda
- pandoc>=2.2
- nodejs
- pip:
  - black
  - cookiecutter
  - editorconfig
  - jupyter_contrib_nbextensions
  - MarkdownPP
  - mypy
  - nbdime
  - panflute
  - vim-vint
