set termencoding=utf-8

" :help gui-font
" :help setting-guifont
if has('gui_gtk3') || has('gui_gtk2')
  set guifont+=CaskaydiaCove\ NF\ 11
  set guifont+=CaskaydiaCove\ NF\ Mono\ 11
  set guifont+=CaskaydiaCove\ Nerd\ Font\ 11
  set guifont+=CaskaydiaCove\ Nerd\ Font\ Mono\ 11
  set guifont+=DejaVu\ Sans\ Mono\ 11
  set guifont+=Consolas\ 11
elseif has('gui_win32')
  if has('directx')
    set renderoptions=type:directx
  endif
  set guifont+=CaskaydiaCove_Nerd_Font:h10:cDEFAULT:qDEFAULT
  set guifont+=CaskaydiaCove_NF:h10:cDEFAULT:qDEFAULT
  set guifont+=CaskaydiaCove_Nerd_Font_Mono:h10:cDEFAULT:qDEFAULT
  set guifont+=CaskaydiaCove_NF_Mono:h10:cDEFAULT:qDEFAULT
  set guifont+=Cascadia_Code:h10:cDEFAULT:qDEFAULT
  set guifont+=Cascadia_Mono:h10:cDEFAULT:qDEFAULT
  set guifont+=Consolas:h10:cDEFAULT:qDEFAULT
endif

" set background=dark
let g:solarized_use16=0

" Disable: Left-hand scrollbar is present when there is a vertically split
" window.
set guioptions-=L
" Disable: Right-hand scrollbar is always present.
set guioptions-=r
" Disable: Include Toolbar.
set guioptions-=T
