set termencoding=utf-8

" :help gui-font
" :help setting-guifont
if has('gui_gtk3') || has('gui_gtk2')
  set guifont+=JetBrains\ Mono\ 13
  set guifont+=Cascadia\ Code\ PL\ 13
  set guifont+=DejaVu\ Sans\ Mono\ 13
  set guifont+=Consolas\ 13
elseif has('gui_win32')
  set guifont+=JetBrains_Mono:h12:cDEFAULT:qDEFAULT
  set guifont+=Cascadia_Code_PL:h12:cDEFAULT:qDEFAULT
  set guifont+=Consolas:h12:cDEFAULT:qDEFAULT
endif

" set background=dark
let g:solarized_use16=0

" Disable: Left-hand scrollbar is present when there is a vertically split
" window.
set guioptions-=L
" Disable: Right-hand scrollbar is always present.
set guioptions-=r
" Disable: Include Toolbar.
set guioptions-=T
